#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-appnope
Version  : 0.1.3
Release  : 1
URL      : https://files.pythonhosted.org/packages/6a/cd/355842c0db33192ac0fc822e2dcae835669ef317fe56c795fb55fcddb26f/appnope-0.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/6a/cd/355842c0db33192ac0fc822e2dcae835669ef317fe56c795fb55fcddb26f/appnope-0.1.3.tar.gz
Summary  : Disable App Nap on macOS >= 10.9
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-appnope-license = %{version}-%{release}
Requires: pypi-appnope-python = %{version}-%{release}
Requires: pypi-appnope-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# `appnope`
Simple package for disabling App Nap on macOS >= 10.9,
which can be problematic.

%package license
Summary: license components for the pypi-appnope package.
Group: Default

%description license
license components for the pypi-appnope package.


%package python
Summary: python components for the pypi-appnope package.
Group: Default
Requires: pypi-appnope-python3 = %{version}-%{release}

%description python
python components for the pypi-appnope package.


%package python3
Summary: python3 components for the pypi-appnope package.
Group: Default
Requires: python3-core
Provides: pypi(appnope)

%description python3
python3 components for the pypi-appnope package.


%prep
%setup -q -n appnope-0.1.3
cd %{_builddir}/appnope-0.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649710724
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-appnope
cp %{_builddir}/appnope-0.1.3/LICENSE %{buildroot}/usr/share/package-licenses/pypi-appnope/578ea6859c2684297064fd9b34b0cb6fb1171be5
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-appnope/578ea6859c2684297064fd9b34b0cb6fb1171be5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
